Repository bitkunst/Nodejs_team_project2, pull requests merged in 2022-04, with the labels that each got.

#50 .
  front/public/js/admin/admin.js
  front/views/admin/admin.html
Labels: backend, frontend

#51 feat : admin/manage/category CRD
  back/public/uploads/img1648784361467.png
  back/routes/admin/adminCg/adminCgController.js
  back/routes/admin/adminCg/index.js
  back/routes/admin/index.js
  front/public/js/admin/admin.js
  front/views/admin/admin.html
  front/views/admin/admin_manageCg.html
Labels: backend, frontend

#52 update : search function url
  back/public/uploads/nodejs31648792041007.jpg
  back/public/uploads/nodejs31648792042373.jpg
  back/public/uploads/nodejs31648792178906.jpg
  back/public/uploads/world-wide-web1648792224422.jpg
  back/routes/search/searchController.js
  front/public/js/search/search.js
  front/views/search/search.html
Labels: backend, frontend

#53 feat : admin page - manage category
  front/public/js/admin/admin.js
  front/views/admin/admin.html
Labels: backend

#54 feat :Edit profile , logout / fix : user/join issue solved
  back/package.json
  back/routes/user/userController.js
  back/routes/user/userRouter.js
  front/middleware/loginAuth.js
  front/package.json
  front/routes/index.js
  front/routes/user/userController.js
  front/routes/user/userRouter.js
  front/views/index.html
  front/views/user/join.html
  front/views/user/kakao.html
  front/views/user/kakaoLogin.html
  front/views/user/login.html
  front/views/user/profile.html
  front/views/user/profileUpdate.html
  front/views/user/update.html
  front/views/user/welcome.html
Labels: backend

#55 feat : quit / view myboard
  .vscode/settings.json
  back/routes/board/main/mainController.js
  back/routes/user/userController.js
  back/routes/user/userRouter.js
  front/public/css/user_agree.css
  front/public/css/user_join.css
  front/public/css/user_login.css
  front/public/css/user_main.css
  front/public/css/user_profile.css
  front/public/css/user_profileUpdate.css
  front/public/css/user_welcome.css
  front/public/js/user/myboard.js
  front/public/js/user/mycomment.js
  front/public/js/user/myscrap.js
  front/public/js/user/user.js
  front/routes/user/userController.js
  front/routes/user/userRouter.js
  front/views/user/_layout.html
  front/views/user/agree.html
  front/views/user/join.html
  front/views/user/login.html
  front/views/user/myboard.html
  front/views/user/mycomment.html
  front/views/user/myscrap.html
  front/views/user/profile.html
  front/views/user/profileBoard.html
  front/views/user/profileUpdate.html
  front/views/user/welcome.html
Labels: backend

#56 feat : view myscrap
  back/routes/user/userController.js
  front/public/css/user_main.css
  front/public/js/user/myscrap.js
  front/views/user/join.html
  front/views/user/profile.html
Labels: backend

#57 board 수정
  back/public/uploads/11649042079145.png
  back/public/uploads/11649053507331.png
  back/public/uploads/DM_20220120102322_0021649053649782.jpg
  back/public/uploads/img1649042567212.png
  back/public/uploads/js1649042567215.png
  back/public/uploads/js1649043406513.png
  back/public/uploads/logo1649043406515.png
  back/public/uploads/nodejs1649043406515.jpeg
  back/public/uploads/스크린샷 2022-02-10 오후 2.13.521649042079150.png
  back/routes/board/boardController.js
  back/routes/board/main/mainController.js
  front/public/admin_css/admin_cg.css
  front/public/css/board_main.css
  front/public/css/board_notice.css
  front/public/css/board_view.css
  front/public/js/board/boardWrite.js
  front/public/js/board/mainList.js
  front/public/js/board/qnaList.js
  front/routes/board/mainBoard/index.js
  front/views/_layout.html
  front/views/admin/admin.html
  front/views/admin/admin_layout.html
  front/views/admin/admin_manageCg.html
  front/views/board/_layout.html
  front/views/board/canNotAccess.html
  front/views/board/main/_layout.html
  front/views/board/main/_layout2.html
  front/views/board/main/list.html
  front/views/board/main/view.html
  front/views/board/qna/list.html
  front/views/board/update.html
Labels: backend, frontend

#58 feat : user profile mycomment
  back/routes/user/userController.js
  front/middleware/adminCheck.js
  front/public/css/user_mycomment.css
  front/public/js/user/mycomment.js
  front/routes/admin/index.js
  front/routes/index.js
  front/routes/user/userController.js
  front/views/user/_layout.html
  front/views/user/login.html
  front/views/user/mycomment.html
  front/views/user/profile.html
Labels: backend, frontend

#59 fix : profile edit errors
  back/routes/user/userController.js
  front/views/user/profile.html
  front/views/user/profileUpdate.html
Labels: backend

#61 feat : header menu create
  back/routes/admin/adminCg/adminCgController.js
  back/routes/board/boardController.js
  back/routes/board/qna/index.js
  back/routes/board/qna/qnaController.js
  front/public/admin_css/admin_cg.css
  front/public/css/layout2.css
  front/public/js/admin/admin.js
  front/public/js/headerMenu.js
  front/routes/board/qna/index.js
  front/views/_layout.html
  front/views/admin/admin.html
  front/views/board/_layout.html
  front/views/board/main/_layout.html
  front/views/board/main/_layout2.html
  front/views/board/qna/view.html
  front/views/board/qna/writeA.html
  front/views/user/_layout.html
Labels: backend, frontend

#62 Jongnam
  .vscode/settings.json
  front/public/css/user_agree.css
  front/public/css/user_join.css
  front/public/css/user_login.css
  front/public/css/user_main.css
  front/public/css/user_mycomment.css
  front/public/css/user_profile.css
  front/public/css/user_profileUpdate.css
  front/public/css/user_welcome.css
  front/views/user/join.html
  front/views/user/login.html
  front/views/user/profile.html
Labels: backend

#64 css login
  front/public/css/user_login.css
  front/public/css/user_main.css
  front/views/user/_layout.html
  front/views/user/login.html
Labels: frontend

#70 feat : oauth login
  back/SQL/table.sql
  back/package.json
  back/public/user_img/default_profileImg.jpg
  back/routes/user/userController.js
  back/routes/user/userRouter.js
  back/server.js
  front/public/admin_css/admin.css
  front/public/js/admin/admin.js
  front/routes/user/userController.js
  front/routes/user/userRouter.js
  front/views/admin/admin.html
  front/views/user/login.html
Labels: backend

#72 feat : welcome,agree css
  back/routes/user/userController.js
  front/public/css/user_agree.css
  front/public/css/user_profile.css
  front/public/css/user_welcome.css
  front/routes/user/userController.js
  front/views/user/_layout.html
  front/views/user/agree.html
  front/views/user/login.html
  front/views/user/profile.html
  front/views/user/profileUpdate.html
  front/views/user/welcome.html
Labels: frontend

#73 fix : kakao login user data
  back/routes/user/userController.js
Labels: backend

#74 fix : profile image upload
  back/routes/user/userController.js
Labels: backend

#75 feat : mainpage front/back, board CSS 수정
  back/public/uploads/수정후1649221957159.jpeg
  back/routes/board/main/index.js
  back/routes/board/main/mainController.js
  back/routes/home/index.js
  back/routes/index.js
  front/public/css/board_main.css
  front/public/css/board_notice.css
  front/public/css/board_view.css
  front/public/css/board_write.css
  front/public/css/homepage.css
  front/public/css/layout.css
  front/public/css/layout2.css
  front/public/img/movie.png
  front/public/img/movie2.png
  front/public/js/board/mainList.js
  front/public/js/homepage.js
  front/routes/board/mainBoard/index.js
  front/routes/index.js
  front/views/_layoutHome.html
  front/views/board/write.html
  front/views/index.html
  front/views/index_backup.html
Labels: backend, frontend

#77 OFGB 미들웨어 프론트->백 수정
  back/routes/index.js
  front/routes/index.js
Labels: backend, frontend

#78 css 수정중
  back/public/uploads/noPic.jpg
  front/public/css/board_main.css
  front/public/css/board_notice.css
  front/public/css/board_view.css
  front/public/css/board_write.css
  front/public/css/homepage.css
  front/public/css/layout.css
  front/public/css/layout2.css
  front/public/img/searchIcon.png
  front/public/js/board/mainList.js
  front/public/js/homepage.js
  front/views/_layout.html
  front/views/_layoutHome.html
  front/views/admin/admin_layout.html
  front/views/board/_layout.html
  front/views/board/main/_layout.html
  front/views/board/main/_layout2.html
  front/views/index.html
  front/views/user/_layout.html
Labels: backend, frontend

#80 feat : search css
  back/routes/search/searchController.js
  front/public/js/search/search.js
  front/public/search_css/search.css
  front/views/search/search.html
Labels: backend, frontend

#81 fix : mainpage css
  back/routes/board/main/mainController.js
  back/routes/home/index.js
  front/public/css/homepage.css
  front/public/img/chatIcon.png
  front/public/js/homepage.js
  front/views/index.html
Labels: frontend

#82 profile css
  .vscode/settings.json
  back/public/profile_img/jongs11121649319600545.jpg
  front/public/css/layout2.css
  front/public/css/user_agree.css
  front/public/css/user_join.css
  front/public/css/user_login.css
  front/public/css/user_main.css
  front/public/css/user_mycomment.css
  front/public/css/user_profile.css
  front/public/css/user_profileUpdate.css
  front/public/css/user_welcome.css
  front/views/user/_layout.html
  front/views/user/join.html
  front/views/user/login.html
  front/views/user/profile.html
  front/views/user/profileUpdate.html
  front/views/user/welcome.html
Labels: frontend

#83 fix : admin css
  front/public/admin_css/admin.css
  front/public/img/admin_bg.jpg
  front/public/js/admin/admin.js
  front/public/search_css/search.css
  front/views/admin/admin.html
Labels: backend, frontend

#84 fix : 댓글 css 수정
  back/public/uploads/viewNoPic.jpeg
  back/routes/comment/commentController.js
  front/public/css/board_view.css
  front/public/js/board/viewAjax.js
  front/public/js/homepage.js
  front/views/board/main/view.html
  front/views/index.html
Labels: frontend

#85 CSS작업 마무리단계
  .vscode/settings.json
  front/public/css/user_login.css
  front/public/css/user_profile.css
  front/public/css/user_welcome_back.css
  front/routes/user/userController.js
  front/routes/user/userRouter.js
  front/views/user/login.html
  front/views/user/welcome.html
  front/views/user/welcome_back.html
Labels: frontend

#87 fix : admin css
  front/public/admin_css/admin.css
Labels: frontend

#88 fix : 버그수정
  front/public/admin_css/admin_cg.css
  front/public/css/board_view.css
  front/routes/board/qna/index.js
  front/views/board/notice/list.html
  front/views/board/qna/list.html
  front/views/board/qna/view.html
  front/views/index.html
Labels: frontend

#91 fix css2
  back/public/profile_img/NaN.jpg
  back/public/profile_img/jongs1121649396147904.jpg
  back/routes/user/userController.js
  back/routes/user/userRouter.js
  front/public/css/user_profileUpdate.css
  front/views/user/profile.html
  front/views/user/profileUpdate.html
Labels: frontend

#92 fix : search css , chat css
  back/SQL/table.sql
  back/public/uploads/041649389762715.jpg
  back/public/uploads/061649388839974.jpg
  back/public/uploads/071649388839992.jpg
  back/public/uploads/071649390049680.jpg
  back/public/uploads/071649390050722.jpg
  back/public/uploads/071649390051360.jpg
  back/public/uploads/081649388840003.jpg
  back/public/uploads/081649389830180.jpg
  back/public/uploads/091649388840019.jpg
  back/public/uploads/091649389936229.jpg
  back/public/uploads/091649389937147.jpg
  back/public/uploads/091649389937484.jpg
  back/public/uploads/091649389937726.jpg
  back/public/uploads/091649389938005.jpg
  back/public/uploads/091649389938206.jpg
  back/public/uploads/091649389938407.jpg
  back/public/uploads/091649389938776.jpg
  back/public/uploads/091649389938974.jpg
  back/public/uploads/091649389939177.jpg
  back/public/uploads/101649388840024.jpg
  front/public/chat_css/chat.css
  front/public/chat_css/chatRoom.css
  front/public/search_css/search.css
  front/views/chat/chat.html
  front/views/chat/chatRoom.html
Labels: frontend

#93 fix : css 및 버그 수정
  back/routes/board/boardController.js
  back/routes/comment/commentController.js
  front/public/css/board_view.css
  front/public/css/user_main.css
  front/public/js/board/mainList.js
  front/public/js/headerMenu.js
  front/public/js/homepage.js
  front/public/js/user/myboard.js
  front/public/js/user/myscrap.js
  front/views/_layout.html
  front/views/_layoutHome.html
  front/views/admin/admin_layout.html
  front/views/board/_layout.html
  front/views/board/main/_layout.html
  front/views/board/main/_layout2.html
  front/views/board/main/list.html
  front/views/board/qna/view.html
  front/views/index.html
  front/views/user/_layout.html
  front/views/user/myboard.html
  front/views/user/myscrap.html
Labels: frontend

#95 fix : 전체적인 css 세부수정 : 상세내용 slack 참조
  back/public/uploads/IMG_16231649401208977.jpg
  back/public/uploads/IMG_16231649401212487.jpg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-34 0031649412244157.jpeg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-35 0051649413564852.jpeg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-35 0051649413569455.jpeg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-35 0061649411609928.jpeg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-35 0061649412446058.jpeg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-35 0061649413200311.jpeg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-36 0081649413400696.jpeg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-36 0101649413437758.jpeg
  back/public/uploads/KakaoTalk_Photo_2022-04-07-20-04-37 0131649413552372.jpeg
  back/routes/admin/adminCg/adminCgController.js
  back/routes/board/boardController.js
  back/routes/board/qna/qnaController.js
  back/routes/comment/commentController.js
  front/public/css/board_main.css
  front/public/css/board_notice.css
  front/public/css/board_write.css
  front/public/css/homepage.css
  front/public/css/user_main.css
  front/public/js/board/boardWrite.js
  front/public/js/board/mainList.js
  front/public/js/board/qnaList.js
  front/public/js/board/viewAjax.js
  front/public/js/homepage.js
  front/routes/board/notice/index.js
  front/routes/board/qna/index.js
  front/views/board/canNotAccess.html
  front/views/board/main/list.html
  front/views/board/qna/view.html
Labels: backend, frontend

#96 fix : admin css
  back/SQL/table.sql
  back/public/img/poster1.jpg
  back/public/img/poster2.jpg
  back/public/img/poster3.jpg
  back/public/img/welcome_img.png
  back/public/profile_img/admin1649404851560.jpg
  back/public/profile_img/bitkunst1649406527309.jpg
  back/public/profile_img/devKong1649408065997.jpg
  back/public/profile_img/hb12341649406384174.jpg
  back/public/profile_img/ingoo1649408418477.jpg
  back/public/profile_img/jongs1649406170271.jpg
  back/public/uploads/051649408480897.jpg
  back/public/uploads/061649408767494.jpg
  back/public/uploads/101649407222247.jpg
  back/public/uploads/121649406729536.jpg
  back/public/uploads/121649406816977.jpg
  back/public/uploads/121649406818620.jpg
  back/public/uploads/121649407034654.jpg
  back/public/uploads/131649408240913.jpg
  back/public/uploads/171649407400972.jpg
  front/public/admin_css/admin.css
  front/public/js/admin/admin.js
Labels: frontend

#97 feat : cursor pointer
  front/views/user/join.html
  front/views/user/login.html
  front/views/user/profile.html
  front/views/user/profileUpdate.html
Labels: frontend

#98 LAST COMMIT
  front/public/css/user_profile.css
Labels: frontend

#99 THE LAST COMMIT : fix notice update
  front/routes/board/notice/index.js
Labels: frontend
